### ISSUE TITLE
Error: network not found

### ISSUE THREAD

**Issue by RebeccaStevens** [Aetrius/Bambulabs-Exporter#7]
I get this error when I run `docker-compose -f monitoring-compose.yml up -d`:

```sh
network bambulabs-exporter_default declared as external, but could not be found
```

~Am I doing something wrong?~

Edit: I was able to resolve the issue with `docker network create bambulabs-exporter_default`. I guess this step was accidently left out of the instructions.

**Comment by Aetrius** [comment]
Everything good once you did that?

**Comment by RebeccaStevens** [comment]
Yeah
